services:

  Kna\YandexCheckoutBundle\Controller\YandexCheckoutController:
    autoconfigure: true
    autowire: true

  kna_yandex_checkout.client:
    public: true
    class: YandexCheckout\Client
    calls:
    - method: setAuth
      arguments:
      - '%kna_yandex_checkout.shop_id%'
      - '%kna_yandex_checkout.secret_key%'

  YandexCheckout\Client:
    alias: kna_yandex_checkout.client